version: '3.8'

services:
  postgres:
    image: postgres:15
    hostname: my-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ${GLOBAL_NETWORK:-postgres}

volumes:
  pgdata:

networks:
  backend: